import React from "react";
import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#A979AA", // Ana ekranlar ile uyumlu arka plan rengi
  },
  profileHeader: {
    width: wp("100%"),
    height: hp("30%"),
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  glowContainer: {
    position: "absolute",
    width: wp("100%"),
    height: hp("60%"),
    top: -hp("10%"),
    alignSelf: "center",
    zIndex: 0,
  },
  glowGradient: {
    width: "100%",
    height: "100%",
    borderRadius: 200,
  },
  starContainer: {
    position: "absolute",
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarContainer: {
    width: hp("15%"),
    height: hp("15%"),
    borderRadius: hp("7.5%"),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 15,
    borderWidth: 4,
    borderColor: "#FFD700",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: hp("7.5%"),
  },
  nameContainer: {
    marginTop: hp("2%"),
    alignItems: "center",
  },
  nameText: {
    fontSize: 22,
    color: "#FFFFFF",
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  usernameText: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.8)",
    marginTop: 5,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 3,
  },
  infoContainer: {
    width: wp("90%"),
    marginTop: hp("3%"),
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  infoGradient: {
    width: "100%",
    padding: wp("5%"),
    borderRadius: 20,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.2)",
    paddingVertical: hp("1.5%"),
  },
  noBorder: {
    borderBottomWidth: 0,
  },
  statusLabel: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 2,
  },
  statusValue: {
    fontSize: 16,
    color: "#FFD700",
    fontWeight: "bold",
  },
  verifiedContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  verifiedText: {
    fontSize: 16,
    color: "#4CAF50",
    fontWeight: "bold",
    marginRight: 5,
  },
  unverifiedText: {
    fontSize: 16,
    color: "#FF5252",
    fontWeight: "bold",
    marginRight: 5,
  },
  membershipContainer: {
    marginTop: hp("2%"),
    width: wp("90%"),
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  membershipGradient: {
    width: "100%",
    padding: wp("5%"),
    borderRadius: 20,
  },
  membershipTitle: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 2,
    marginBottom: hp("1.5%"),
  },
  progressContainer: {
    marginTop: hp("1%"),
    width: "100%",
    height: 10,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#FFD700",
  },
  logoutButton: {
    marginTop: hp("4%"),
    width: wp("90%"),
    height: hp("6%"),
    borderRadius: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  logoutGradient: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  logoutText: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "bold",
    marginLeft: 10,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 2,
  },
  moonContainer: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: hp("2%"),
    right: wp("10%"),
    shadowColor: "#FFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    zIndex: 10,
  },
  editableContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  editIcon: {
    marginLeft: 8,
  },
});

export default styles;
