import React from "react";
import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    padding: 16,
  },
  backgroundImage: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
  },
  profileHeader: {
    width: wp("100%"),
    height: hp("30%"),
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  moonSceneContainer: {
    position: "absolute",
    width: wp("100%"),
    height: hp("30%"),
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  moonContainer: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    top: hp("2%"),
    right: wp("10%"),
    shadowColor: "#FFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    zIndex: 10,
  },
  moonGlow: {
    position: "absolute",
    width: wp("40%"),
    height: wp("40%"),
    borderRadius: wp("20%"),
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    zIndex: 5,
    top: hp("2%"),
    right: wp("5%"),
  },
  starContainer: {
    position: "absolute",
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 8,
  },
  avatarContainer: {
    width: hp("15%"),
    height: hp("15%"),
    borderRadius: hp("7.5%"),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 15,
    borderWidth: 4,
    borderColor: "#FFD700",
    overflow: "hidden",
    zIndex: 20,
    marginTop: hp("2%"),
  },
  defaultAvatarContainer: {
    width: "100%",
    height: "100%",
    borderRadius: hp("7.5%"),
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: hp("7.5%"),
  },
  nameContainer: {
    marginTop: hp("2%"),
    alignItems: "center",
    zIndex: 20,
  },
  nameText: {
    fontSize: 22,
    color: "#FFFFFF",
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.7)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  usernameText: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.9)",
    marginTop: 5,
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 3,
  },
  infoContainer: {
    width: wp("90%"),
    marginTop: hp("2%"),
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 15,
  },
  infoGradient: {
    width: "100%",
    padding: wp("5%"),
    borderRadius: 20,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.2)",
    paddingVertical: hp("1.5%"),
  },
  noBorder: {
    borderBottomWidth: 0,
  },
  statusLabel: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 2,
  },
  statusValue: {
    fontSize: 16,
    color: "#FFD700",
    fontWeight: "bold",
  },
  verifiedContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  verifiedText: {
    fontSize: 16,
    color: "#4CAF50",
    fontWeight: "bold",
    marginRight: 5,
  },
  unverifiedText: {
    fontSize: 16,
    color: "#FF5252",
    fontWeight: "bold",
    marginRight: 5,
  },
  membershipContainer: {
    marginTop: hp("2%"),
    width: wp("90%"),
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 15,
  },
  membershipGradient: {
    width: "100%",
    padding: wp("5%"),
    borderRadius: 20,
  },
  membershipTitle: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 2,
    marginBottom: hp("1.5%"),
  },
  progressContainer: {
    marginTop: hp("1%"),
    width: "100%",
    height: 10,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#FFD700",
  },
  logoutButtonContainer: {
    marginTop: hp("4%"),
    marginBottom: hp("5%"),
    width: wp("90%"),
    height: hp("7%"),
    borderRadius: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  logoutButton: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    borderRadius: 15,
  },
  logoutText: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "bold",
    marginLeft: 10,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonIconContainer: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: wp("3%"),
  },
  editableContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  editIcon: {
    marginLeft: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 16,
    color: "#FFFFFF",
    marginTop: 15,
    fontWeight: "500",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 2,
  },
});

export default styles;
