import React from "react";
import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    padding: 16,
    backgroundColor: "#A979AA",
  },
  firstContainer: {
    marginTop: hp("10%"),
    width: wp("90%"),
    height: hp("50%"),
  },
  mistikContainer: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 15,
    position: "relative",
  },
  moonContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: hp("4%"),
    shadowColor: "#FFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.8,
    shadowRadius: 15,
  },
  glowContainer: {
    position: "absolute",
    width: wp("100%"),
    height: hp("60%"),
    top: -hp("10%"),
    alignSelf: "center",
    zIndex: 0,
  },
  glowGradient: {
    width: "100%",
    height: "100%",
    borderRadius: 200,
  },
  starContainer: {
    position: "absolute",
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  mistikTitle: {
    fontWeight: "bold",
    fontSize: 24,
    color: "#FFFFFF",
    marginBottom: 15,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
    zIndex: 2,
  },
  mistikText: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.9)",
    textAlign: "center",
    marginHorizontal: 20,
    zIndex: 2,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 3,
  },
  // Form için yeni stiller
  formContainer: {
    width: wp("90%"),
    marginTop: hp("2%"),
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  formGradient: {
    width: "100%",
    height: "100%",
    padding: wp("5%"),
    borderRadius: 20,
  },
  inputGroupContainer: {
    width: "100%",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 10,
    marginBottom: hp("2%"),
    paddingHorizontal: wp("3%"),
    height: hp("6%"),
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  textAreaContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 10,
    marginBottom: hp("2%"),
    paddingHorizontal: wp("3%"),
    paddingTop: hp("1.5%"),
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  inputIcon: {
    marginRight: wp("2%"),
  },
  input: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "500",
  },
  textArea: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 16,
    minHeight: hp("15%"),
    textAlignVertical: "top",
  },
  submitButtonContainer: {
    marginTop: hp("1%"),
    borderRadius: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: hp("6%"),
    borderRadius: 15,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: wp("2%"),
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  loadingIcon: {
    transform: [{ rotate: "0deg" }],
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: wp("2%"),
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});

export default styles;
